/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author rifaul
 */
public class PERSEGI extends javax.swing.JFrame {

    /**
     * Creates new form PERSEGI
     */
    public PERSEGI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPersegi = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        ALUAS = new javax.swing.JLabel();
        AKELILING = new javax.swing.JLabel();
        Asisi = new javax.swing.JTextField();
        Jhitung = new javax.swing.JButton();
        Jreset = new javax.swing.JButton();
        Jkembali = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPersegi.setText("PERSEGI");
        jPersegi.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jPersegiAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jLabel1.setText("SISI");

        ALUAS.setText("LUAS");

        AKELILING.setText("KELILING");

        Asisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AsisiActionPerformed(evt);
            }
        });

        Jhitung.setText("HITUNG");
        Jhitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JhitungActionPerformed(evt);
            }
        });

        Jreset.setText("RESET");
        Jreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JresetActionPerformed(evt);
            }
        });

        Jkembali.setText("KEMBALI");
        Jkembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JkembaliActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(180, 180, 180)
                                .addComponent(jPersegi))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Jreset)
                                            .addComponent(Asisi, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(AKELILING, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(ALUAS))
                                        .addGap(0, 0, Short.MAX_VALUE)))))
                        .addGap(13, 13, 13))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Jhitung)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(Jkembali)
                .addGap(21, 21, 21))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPersegi)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(Asisi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Jhitung)
                    .addComponent(Jreset)
                    .addComponent(Jkembali))
                .addGap(34, 34, 34)
                .addComponent(ALUAS)
                .addGap(18, 18, 18)
                .addComponent(AKELILING)
                .addContainerGap(96, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPersegiAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jPersegiAncestorAdded

    }//GEN-LAST:event_jPersegiAncestorAdded

    private void AsisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AsisiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AsisiActionPerformed

    private void JkembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JkembaliActionPerformed
      new Home().setVisible(true);
      dispose();
    }//GEN-LAST:event_JkembaliActionPerformed

    private void JhitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JhitungActionPerformed
int sisi = Integer.parseInt(Asisi.getText());
int luas = sisi * sisi;
int keliling = 4 * sisi;
ALUAS.setText("LUAS : "+luas);
AKELILING.setText("KELILING : "+keliling);
    }//GEN-LAST:event_JhitungActionPerformed

    private void JresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JresetActionPerformed
    Asisi.setText("");
    Asisi.setText(null);
    Asisi.setText(null);
    Asisi.setText(null);
    }//GEN-LAST:event_JresetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PERSEGI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PERSEGI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PERSEGI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PERSEGI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PERSEGI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AKELILING;
    private javax.swing.JLabel ALUAS;
    private javax.swing.JTextField Asisi;
    private javax.swing.JButton Jhitung;
    private javax.swing.JButton Jkembali;
    private javax.swing.JButton Jreset;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jPersegi;
    // End of variables declaration//GEN-END:variables
}
